title: My GitHub Pages Site
description: Personal site / portfolio

theme: null

markdown: kramdown

include:
  - _includes
  - _layouts

nav:
  - name: Home
    url: 
  - name: Projects
    url: projects

baseurl: "/Portfolio"

collections:
  projects:
    output: true